### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Coysh** [Nikeev/sesdashboard#12]
Attempted an install via the Marketplace.
Had to edit the default security group, as it was wrong.
Get to the login page, try default login details and then get the following:

![Screenshot 2021-04-25 at 14 33 45](https://user-images.githubusercontent.com/5764356/115995469-3de48100-a5d3-11eb-98b1-c568f99203f6.png)

**Comment by Nikeev** [comment]
Hello!

Could you clarify what instance type did you select? 
And what security group changes you had to make? As I can see, now it is configured to 22 and 80 ports.

**Comment by Coysh** [comment]
Its a nano instance. Security gorup was the recommended one
-
Tim Coysh | Freelance web designer | timcoysh.co.uk | 07817 380 659

**Comment by Nikeev** [comment]
It seems that t2.nano is not enough to run sesdashboard. You could recreate server with at least t2.micro or try to create swap file for your current t2.nano, it should help.
I will remove t2.nano from install options for now.

**Comment by Coysh** [comment]
@Nikeev Great' t2.micro seems to be doing the job!
