### ISSUE TITLE
Letsencrypt SSL

### ISSUE THREAD

**Issue by pareeohnos** [Nikeev/sesdashboard#31]
I've just setup SESDashboard using the AWS EC2 image, and everything is up and running, but I want to get it running over SSL. One approach would obviously be to setup a load balancer and have it handle the certificate, but this incurs additional cost so I was hoping to setup Letsencrypt instead.

Unfortunately, because SESDashboard is using Docker images for the various components, this complicates things considerably. Do you have a simple way to set this up, or is it going to be quite convoluted?

**Comment by pareeohnos** [comment]
Just built a new EC2 image without using docker

**Comment by MaximilianKohler** [comment]
https://github.com/Nikeev/sesdashboard/issues/52
