### ISSUE TITLE
How can we download reports?

### ISSUE THREAD

**Issue by j-solanki** [Nikeev/sesdashboard#32]
Is there a way to download reports?

**Comment by Nikeev** [comment]
Hello!

Unfortunately, reports are not implemented yet.

**Comment by CMM1305** [comment]
Do you have an ETA when reports will be ready?

**Comment by Nikeev** [comment]
I've created a new Discussion #39 for Export feature. Closing this issue.

**Comment by CMM1305** [comment]
Hi,
I'm using an Amazon AMI image. I've just logged in via SSH and ran git pull plus the 4 docker commands you mention in the docs:
$ docker exec -it sesdashboard-php-fpm composer install
$ docker exec -it sesdashboard-php-fpm ./bin/console doctrine:migrations:migrate -n
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:clear
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:warmup

But it doesn't show a version number anywhere once logged in so I'm not sure if I'm on the latest version. The Reports menu still has "TODO" next to it and has a link of #

Is there something different I have to do to update?

Thanks in advance

**Comment by Nikeev** [comment]
Hello!

Yes, update commands are correct. If you wish to use new Activity export feature, it's not in Reports menu. It's in Activity page inside Filters form. Sorry if it is confusing, but it uses same Activity filter so I decided to place it there.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1555773/149655267-e6cd8583-2150-4f2a-9ab1-0f3fe4443fa0.png">
