### ISSUE TITLE
Internal Server Error when configuration sets name is not "Tracking"

### ISSUE THREAD

**Issue by juampa** [Nikeev/sesdashboard#35]
When I create a different configuration set with any name different to "Tracking" I get a Error 500.  Is it hardcoded somewhere?

**Comment by Nikeev** [comment]
Hello!

Could you clarify which page causes Error 500? Is it webhook or Send test email page?
Also, it will be helpful if you could provide specific error which could be found at APP/var/log/prod.log

Thanks!

**Comment by juampa** [comment]
Sorry Nikeev. I forgot to activate "raw message delivery" on the Amazon SES Configuration Set. It works perfect now.

**Comment by juampa** [comment]
Not an issue.
