### ISSUE TITLE
Activity UI Tab not working

### ISSUE THREAD

**Issue by yogesh-bangar** [Nikeev/sesdashboard#43]
Hi,
I have setup sesdashboard on EC2 instance and also linked with AWS SNS, I could see the data in Dashboard, but I am not able to see data on Activity Tab. When I download the report, the data is reflected in it but not on the Activity Tab UI. 
I've attached the screen shoot for the same.
Please look into it ASAP
![Dashboard(Working fine)](https://user-images.githubusercontent.com/99468917/166196157-e6920a36-3a7d-4680-9061-47b04e8c7f1d.png)
![Activity(Not Working)](https://user-images.githubusercontent.com/99468917/166196180-fe68da34-c08c-41ef-b97a-32c7ebc75a5c.png)
When I inspected the Activity UI console, below is the error I'm seeing. 
![Activity(When Inspected console)](https://user-images.githubusercontent.com/99468917/166196601-68fd7517-ef07-4ee0-92fa-8c8f3d940a13.png)

**Comment by Nikeev** [comment]
Hello! Sorry for late reply.
It's quite strange about 404 error for api url. Could you please clear all caches
```
$ ./bin/console cache:clear
$ ./bin/console cache:warmup
```
Or for Docker
```
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:clear
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:warmup
```
And try again? Also please try to open http://<you server>/activity/list/api?page=1&limit=10 in browser. Do you see any json response or the same 404 error?

**Comment by yogesh-bangar** [comment]
Hi Nikeev,
As suggested by you, ran the command for clearing all caches. But I still face the same issue(404 error) as attached in the previous screen shot.
I also tried to open "http:///activity/list/api?page=1&limit=10" in browser and I am getting the Json response in return. The json data is the actual data which I need to get displayed in the Activity UI.

**Comment by yogesh-bangar** [comment]
Nikeev thanks for your response, the issue is resolved. The issue was in apache configuration (.htaccess file) where it was not allowing some redirects.
