### ISSUE TITLE
Docker upgrade fails

### ISSUE THREAD

**Issue by nicolopez77** [Nikeev/sesdashboard#44]
I'm using the version from AWS marketplace, and when I try to upgrade following the documentation:
docker exec -it sesdashboard-php-fpm composer install

I receive the following error message:

  [Composer\Downloader\TransportException]
  curl error 6 while downloading https://flex.symfony.com/versions.json: Could not resolve host: flex.symfony.com

It looks like it's using the old Flex infrastructure, are there instructions to update it?

**Comment by Nikeev** [comment]
Hello!
Unfortunately, I can't reproduce an error. Fresh install works fine, so maybe it is an issue with update flow.
There was another issue with Dockerfile for php recently, maybe they are related.
Please try `git pull` fresh changes again, make sure that composer.json, composer.lock, symfony.lock were updated with actual versions.
Run `docker-compose build php-fpm --no-cache`
And other steps from upgrade docs
```
$ docker exec -it sesdashboard-php-fpm composer install
$ docker exec -it sesdashboard-php-fpm ./bin/console doctrine:migrations:migrate -n
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:clear
$ docker exec -it sesdashboard-php-fpm ./bin/console cache:warmup
```
