### ISSUE TITLE
Unable to create a new user.

### ISSUE THREAD

**Issue by PedroSilveiraMalaquias** [Nikeev/sesdashboard#49]
I am trying to run the create user command **./bin/console app:create-user --admin** in sesdashboard directory, and I am getting a "/usr/bin/env: ‘php’: No such file or directory" error.  I installed the dashboard from the AWS Marketplace. 
Does anyone know how to fix it?

**Comment by Nikeev** [comment]
Hello!

AWS Marketplace app is running with Docker, so no local php installed. You should run commands with **docker exec -it sesdashboard-php-fpm** prefix. So in your case it will be:

`docker exec -it sesdashboard-php-fpm ./bin/console app:create-user --admin`

**Comment by PedroSilveiraMalaquias** [comment]
Thank you so much @Nikeev, it worked! I am closing this issue.
