### ISSUE TITLE
Update to PHP 8.1

### ISSUE THREAD

**Issue by jgimenez** [Nikeev/sesdashboard#50]
The PHP version used is outdated and no longer receiving updates. The PHP version should be updated.

**Comment by Nikeev** [comment]
Hello! Yes, I'm planning to update PHP version, but can't give you any estimation time when it will be ready :(

**Comment by Nikeev** [comment]
Updated docker image to php 8.1

Run `docker-compose build --no-cache php-fpm` and restart containers
