### ISSUE TITLE
MySQL index missing

### ISSUE THREAD

**Issue by jgimenez** [Nikeev/sesdashboard#51]
After a few thousand emails are stored in the database the application becomes sluggish, up to the point it just times out.

Creating this index resolves the issue:

```SQL
CREATE INDEX idx_project_id_message_id ON email(project_id, message_id) USING HASH;
```

**Comment by Nikeev** [comment]
Hello!

Thanks for you suggestion! I'll add it with closest updates

**Comment by Nikeev** [comment]
Hello!

Added a new migration with index on email table.

Run `./bin/console doctrine:migrations:migrate -n` to apply migration
