### ISSUE TITLE
SNS Confirmation

### ISSUE THREAD

**Issue by jedmundstephens** [Nikeev/sesdashboard#54]
I must be missing a step somewhere, but the SNS Subscription never completes.  When I curl the /webhook/ address, I get an "ERROR 405: Method Not Allowed".

I'm using the docker installation.

[Edit]: Apologies. It looks like it was an http/https issue on my part. Things seem to be working now.

**Comment by sabativi** [comment]
Can you be more precise, I am missing the same things....

**Comment by jedmundstephens** [comment]
Not sure if it is helpful, but...
I was sending the confirmation to both https and http. The server was
trying to answer on https, but it wasn't getting through because I didn't
have my dns set yet - I was just using IP while testing. Basically the ssl
cert on the server wasn't matching the IP address. I switched it to
answering on http only, and it worked after that. After getting the dns
set, I switched over to https, and it is working there now too.
