### ISSUE TITLE
Multiple Domains and Pro

### ISSUE THREAD

**Issue by Cave-Johnson** [Nikeev/sesdashboard#55]
Project looks very promising-  few questions?
- What does pro offer over the free version?
- Does this support analytics from multiple sending domains?

**Comment by Nikeev** [comment]
Hello!

With Pro version you could create multiple projects (sending domains) for analytics and multiple users with own projects. You could check demo version: http://pro.sesdashboard.com

**Comment by Cave-Johnson** [comment]
How do i purchase pro?

**Comment by Cave-Johnson** [comment]
Whats the setup process for multiple domains in the same account? Do i need to create separate configuration sets and SNS queues or does one set work for multiple domains and SESdashboard can separate them?

**Comment by Nikeev** [comment]
Hello!

To purchase Pro version please contact help@sesdashboard.com

At the SesDashboard app side - multiple domains are new projects with own WebHook urls. Yes, you should attach them to separate configuration sets and SNS queues, so data will be collected individually.
