### ISSUE TITLE
Upgrade failed on Amazon AMI Image

### ISSUE THREAD

**Issue by CMM1305** [Nikeev/sesdashboard#56]
Hi,
I tried to upgrade my SES Dashboard instance to the new version. However, after running git pull, I then tried to run the following commands:
docker exec -it sesdashboard-php-fpm composer install
docker exec -it sesdashboard-php-fpm ./bin/console doctrine:migrations:migrate -n
docker exec -it sesdashboard-php-fpm ./bin/console cache:clear
docker exec -it sesdashboard-php-fpm ./bin/console cache:warmup

The top command didn't work as it was complaining about the PHP Version. I then found another issue on here that said to run docker-compose build --no-cache php-fpm. This upgraded PHP to 8.1 but I'm still unable to complete the other commands.

I managed to run the composer command but at the end is gives an error:
PHP Fatal error:  Declaration of ContainerHKkKLAq\EntityManager_9a5be93::refresh($entity) must be compatible with Doctrine\ORM\EntityManager::refresh($entity, ?int $lockMode = NULL) in /application/var/cache/prod/ContainerHKkKLAq/proxy-classes.php on line 128

This same error occurs if I try and run the other commands.

Any ideas?

Could I somehow backup the database and redownload everything from scratch?

Kind regards,

Chris

**Comment by Nikeev** [comment]
Hello!

An error looks like cache issue. In case the command
`docker exec -it sesdashboard-php-fpm ./bin/console cache:clear`
doesn't work, you could try to clear cache manually:
`sudo rm -rf var/cache`

Yes, you could get an access to database by uncommenting the mysql `ports` section inside the `docker-compose.yml` file. And then restart it. After that you will have mysql available outside the Docker container. The file `.env.local` stores connection credentials that you could use to connect through, for example, MySQL Workbench and make a database dump. For security reasons it's better to comment `ports` section back and restart.

**Comment by CMM1305** [comment]
Hi,

Thanks for getting back to me. I've tried the manual clear cache command you suggested and after doing it manually, I was then able to run the normal migration, cache clear and cache warmup commands and my instance is now back online.

Thanks ever so much for your help, much appreciated.

Chris
