### ISSUE TITLE
Subject is missing

### ISSUE THREAD

**Issue by mtebele** [Nikeev/sesdashboard#57]
I'm sending emails with SES templates, but the Subject in the activity is N/A. All the other fields are ok.

![Captura de Pantalla 2023-01-01 a la(s) 20 44 07](https://user-images.githubusercontent.com/4268555/210187690-3d0a35f8-4242-4416-9e8b-4e7bf96224fb.png)

![Captura de Pantalla 2023-01-01 a la(s) 20 44 16](https://user-images.githubusercontent.com/4268555/210187692-7c93c143-a883-4c4b-804b-f003b3475614.png)

![Captura de Pantalla 2023-01-01 a la(s) 20 45 28](https://user-images.githubusercontent.com/4268555/210187713-7c5ab27e-88b5-48a9-bcc5-39b684aa80fb.png)

**Comment by Nikeev** [comment]
Hello!

Unfortunately I didn't test templates emails, so I can't tell you what could be happening. 

Could you provide me with a json data from Send event under Email details modal? You could hide any sensitive data, I just need to look at json structure.

Thanks

**Comment by mtebele** [comment]
> Hello!
> 
> Unfortunately I didn't test templates emails, so I can't tell you what could be happening.
> 
> Could you provide me with a json data from Send event under Email details modal? You could hide any sensitive data, I just need to look at json structure.
> 
> Thanks

It's empty. Here I send you the full message detail:

![image](https://user-images.githubusercontent.com/4268555/211026883-d205246b-e564-45fc-a46f-fe0eefc22d74.png)

**Comment by Nikeev** [comment]
Hello!

Sorry for the late reply. I found an issue. Now it should be fixed
