### ISSUE TITLE
Installing to a shared hosting enviroment

### ISSUE THREAD

**Issue by Robmobius** [Nikeev/sesdashboard#7]
I asked my webhost to install this on a subdomain. They tried but could not with the following comment

"However, it turned out that the application is developed to work with the local host or the IP Address of the Server which is not possible since you are using one of our Shared Hosting Environments. Another option is for you to contact the developer of the application and ask how can we configure it to work under a custom URL"

Is it possible to get this installed in a shared environment?

**Comment by Nikeev** [comment]
Hello!

Yes, it is possible to install to a shared hosting.

Steps may vary depend on specific shared hosting, but common steps are:
1. Create new site project
2. Git clone sesdashboard into it (or upload files manually)
3. Run `$ composer install` to download packages
4. If your web hosting web root is not `/public`, create a symlink to it. For example, my shared hosting provider has `public_html/` folder ad web root for index.php by default. So it will be 
`$ ln -s ~/sesdashboard/public ~/sesdashboard/public_html`
5. At the moment this package doesn't include .htaccess config file for Apache servers, but you could download default from [https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess](url) and place it into `public/` folder. In the future I'll include it into this repo.
6. Copy `.env` file into `.env.local` and fill MySQL parameters and change `APP_ENV` to `prod`

Other steps like db install and user creation are the same: https://github.com/Nikeev/sesdashboard#regular-installation

This should work.

**Comment by Robmobius** [comment]
Superb, thanks Nikeev.

I have shared these guidelines with my host, I'll report back on how they get on.

**Comment by Robmobius** [comment]
Successfully installed but the UI seems very rudimentary when compared with screen grabs on https://sesdashboard.com/

I suspect something has not installed correctly.

**Comment by Nikeev** [comment]
As we contacted by email, an issue was resolved.
