### ISSUE TITLE
Unnecessary .htaccess file

### ISSUE THREAD

**Issue by jgimenez** [Nikeev/sesdashboard#8]
Since the provided server configuration is for nginx, .htaccess files are not required.

https://github.com/Nikeev/sesdashboard/blob/master/public/.htaccess

This gives the impression that the web server is misconfigured, even if it doesn't introduce any issues.

**Comment by Nikeev** [comment]
Hello!

Yes, .htaccess file is not required by main setup configuration, but some users (issues #7, #2) could install SesDashboard app on shared hosting with Apache only provided. So .htaccess was added to allow to run application on Apache servers too.

**Comment by jgimenez** [comment]
hi! Maybe then this file could be residing outside the `public` folder, or remove access to the file with the nginx config file?

**Comment by Nikeev** [comment]
Remove access to the file with the nginx config file sounds good. I'll add it to my todo list. Thanks

**Comment by Nikeev** [comment]
Hello, added commit 511ef06415ce250b7cd9ca0b884d1edfb433c54b with `.htaccess` file restriction in nginx config.

**Comment by MaximilianKohler** [comment]
Hmm, that's for docker only. I'm installing this not with docker and my server software is Centmin Mod. They have a script that automatically detects `.htaccess` files and creates nginx-equivalent rules https://community.centminmod.com/threads/autoprotect-sh-apache-htaccess-check-migration-to-nginx-deny-all.7308/.

I'm guessing that I should just rename the `.htaccess` file so it gets ignored completely?

**Comment by Nikeev** [comment]
You could remove `.htaccess` if you don't use Apache.
